### PR TITLE
Added mac spoofing to the script

### PR DESCRIPTION
**Pull request by Baitinq**
Added macchanger to the script. It now changes the interfaces mac at the script's startup and reverts it to the original on the script's shutdown. Also added chngmac command to the script.
`torctl chngmac`

### CODE REVIEW

**Comment by sepehrdaddev** [comment]
@Baitinq Thank you for your contribution to this project,
unfortunately I have to deny your pull request.
The reason is the code is not stable and it will cause undefined behavior.

**Comment by Baitinq** [comment]
Sure, no problem. May I ask how the code is unstable as to be able to fix those mistakes in future projects? Thanks

**Comment by sepehrdaddev** [comment]
@Baitinq  Sure, for some reason macchanger give some error on some wireless devices which I have tested.
I'm checking the macchanger source code to see the reason,
but at the moment I prefer not to add it to the script.
now if the error was false then the code will be added.
Another thing is that I'm adding the mac spoofing to all interfaces and not the default.

**Comment by Baitinq** [comment]
@sepehrdaddev True, it would be much better to change the mac address on all interfaces. (Im not sure about the macchanger error, altough I only tested it with two different network interfaces)

**Comment by sepehrdaddev** [comment]
@Baitinq I don't get it either but when I understand the error I will let you know.

**Pull request closed without merging**
